import { Author } from "./author.model";

export const AUTHORS: Author[] = [
	{
		id: 1,
		name: "F. Scott Fitzgerald",
		birthDate: "1896-09-24",
		photoUrl: "assets/images/author1.jpg",
		workCount: 5,
		topSubjects: ["Fiction", "Classic", "Literature", "Drama", "Poetry"],
	},
	{
		id: 2,
		name: "George Orwell",
		birthDate: "1903-06-25",
		photoUrl: "assets/images/author2.jpg",
		workCount: 7,
		topSubjects: [
			"Dystopian",
			"Political Fiction",
			"Science Fiction",
			"Satire",
			"Non-fiction",
		],
	},
	{
		id: 3,
		name: "Harper Lee",
		birthDate: "1926-04-28",
		photoUrl: "assets/images/author3.jpg",
		workCount: 2,
		topSubjects: [
			"Fiction",
			"Southern Gothic",
			"Coming-of-age",
			"Drama",
			"Literature",
		],
	},
	{
		id: 4,
		name: "Jane Austen",
		birthDate: "1775-12-16",
		photoUrl: "assets/images/author4.jpg",
		workCount: 6,
		topSubjects: ["Romance", "Classic", "Literature", "Fiction", "Drama"],
	},
	{
		id: 5,
		name: "Herman Melville",
		birthDate: "1819-08-01",
		photoUrl: "assets/images/author5.jpeg",
		workCount: 9,
		topSubjects: ["Adventure", "Classic", "Fiction", "Drama", "Literature"],
	},
	{
		id: 7,
		name: "Aldous Huxley",
		birthDate: "1894-07-26",
		photoUrl: "assets/images/author7.jpeg",
		workCount: 6,
		topSubjects: ["Dystopian", "Science Fiction", "Political Fiction", "Satire", "Philosophy"],
	},
	{
		id: 8,
		name: "Ray Bradbury",
		birthDate: "1920-08-22",
		photoUrl: "assets/images/author8.jpg",
		workCount: 5,
		topSubjects: ["Dystopian", "Science Fiction", "Fantasy", "Literature", "Drama"],
	},
	{
		id: 9,
		name: "J.R.R. Tolkien",
		birthDate: "1892-01-03",
		photoUrl: "assets/images/author9.jpg",
		workCount: 15,
		topSubjects: ["Fantasy", "Adventure", "Literature", "Mythology", "Historical Fiction"],
	},
	{
		id: 10,
		name: "Paulo Coelho",
		birthDate: "1947-08-24",
		photoUrl: "assets/images/author10.jpeg",
		workCount: 20,
		topSubjects: ["Philosophy", "Adventure", "Fiction", "Spirituality", "Literature"],
	},
	{
		id: 11,
		name: "Leo Tolstoy",
		birthDate: "1828-09-09",
		photoUrl: "assets/images/author11.jpg",
		workCount: 8,
		topSubjects: ["Historical Fiction", "Classic", "Literature", "Philosophy", "Drama"],
	},
	{
		id: 12,
		name: "Oscar Wilde",
		birthDate: "1854-10-16",
		photoUrl: "assets/images/author12.jpg",
		workCount: 9,
		topSubjects: ["Fiction", "Classic", "Drama", "Poetry", "Satire"],
	},
];
