import { Book } from "./book.model";

export const BOOKS: Book[] = [
	{
		id: 1,
		title: "The Great Gatsby",
		authors: [
			{ name: "F. Scott Fitzgerald", birthYear: 1896, deathYear: 1940 },
		],
		first_publish_year: 1925,
		cover_id: 1111,
		edition_count: 5,
		subjects: ["Fiction", "Classic", "Finance"],
		noOfPages: 225,
	},
	{
		id: 2,
		title: "Brave New World",
		authors: [{ name: "George Orwell", birthYear: 1903, deathYear: 1950 }],
		first_publish_year: 1949,
		cover_id: 2222,
		edition_count: 7,
		subjects: ["Dystopian", "Political Fiction", "Finance"],
		noOfPages: 799,
	},
	{
		id: 3,
		title: "To Kill a Mockingbird",
		authors: [{ name: "Harper Lee", birthYear: 1926, deathYear: 2016 }],
		first_publish_year: 1960,
		cover_id: 54321,
		edition_count: 8,
		subjects: ["Fiction", "Historical"],
		noOfPages: 6125,
	},
	{
		id: 4,
		title: "Pride and Prejudice",
		authors: [{ name: "Jane Austen", birthYear: 1775, deathYear: 1817 }],
		first_publish_year: 1813,
		cover_id: 4444,
		edition_count: 12,
		subjects: ["Romance", "Classic", "Finance"],
		noOfPages: 900,
	},
	{
		id: 5,
		title: "Moby Dick",
		authors: [{ name: "Herman Melville", birthYear: 1819, deathYear: 1891 }],
		first_publish_year: 1851,
		cover_id: 5555,
		edition_count: 9,
		subjects: ["Adventure", "Classic", "Finance"],
		noOfPages: 450,
	},
	{
		id: 6,
		title: "The Catcher in the Rye",
		authors: [{ name: "J.D. Salinger", birthYear: 1919, deathYear: 2010 }],
		first_publish_year: 1951,
		cover_id: 6666,
		edition_count: 10,
		subjects: ["Fiction", "Classic", "Finance"],
		noOfPages: 799,
	},
	{
		id: 7,
		title: "Brave New World",
		authors: [{ name: "Aldous Huxley", birthYear: 1894, deathYear: 1963 }],
		first_publish_year: 1932,
		cover_id: null,
		edition_count: 6,
		subjects: ["Dystopian", "Science Fiction", "Finance"],
		noOfPages: 2300,
	},
	{
		id: 8,
		title: "Fahrenheit 451",
		authors: [{ name: "Ray Bradbury", birthYear: 1920, deathYear: 2012 }],
		first_publish_year: 1953,
		cover_id: null,
		edition_count: 5,
		subjects: ["Dystopian", "Science Fiction", "Finance"],
		noOfPages: 655,
	},
	{
		id: 9,
		title: "The Hobbit",
		authors: [{ name: "J.R.R. Tolkien", birthYear: 1892, deathYear: 1973 }],
		first_publish_year: 1937,
		cover_id: 9999,
		edition_count: 15,
		subjects: ["Fantasy", "Adventure", "Finance"],
		noOfPages: 1225,
	},
	{
		id: 10,
		title: "The Alchemist",
		authors: [{ name: "Paulo Coelho", birthYear: 1947 }],
		first_publish_year: 1988,
		cover_id: 9999,
		edition_count: 20,
		subjects: ["Adventure", "Philosophy", "Finance"],
		noOfPages: 941,
	},
	{
		id: 11,
		title: "War and Peace",
		authors: [{ name: "Leo Tolstoy", birthYear: 1828, deathYear: 1910 }],
		first_publish_year: 1869,
		cover_id: 55555,
		edition_count: 8,
		subjects: ["Historical Fiction", "Classic", "Finance"],
		noOfPages: 1160,
	},
	{
		id: 12,
		title: "The Picture of Dorian Gray",
		authors: [{ name: "Oscar Wilde", birthYear: 1854, deathYear: 1900 }],
		first_publish_year: 1890,
		cover_id: 66666,
		edition_count: 9,
		subjects: ["Fiction", "Classic", "Finance"],
		noOfPages: 566,
	},
];
